name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pyinstaller webdriver-manager python-dotenv selenium pandas openpyxl

      - name: Build SalesNavScraper.exe
        run: |
          pyinstaller --clean --onefile --name SalesNavScraper --icon assets/scraper.ico src/salesnav_scraper.py

      - name: Package bundle
        shell: powershell
        run: |
          Remove-Item -Recurse -Force bundle -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path bundle
          Copy-Item dist\SalesNavScraper.exe bundle\
          Copy-Item cred.env bundle\
          Copy-Item data\links.xlsx bundle\
          Compress-Archive -Path bundle\* -DestinationPath SalesNavScraper-windows.zip

      - name: Upload Windows bundle
        uses: actions/upload-artifact@v4
        with:
          name: salesnavscraper-windows
          path: SalesNavScraper-windows.zip
